repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^capture_tests/expected_captures\.txt$
      - id: end-of-file-fixer
        exclude: ^capture_tests/expected_captures\.txt$
      - id: check-yaml

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.6
    hooks:
      - id: markdown-link-check
        args: [-q]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^capture_tests/expected_captures\.txt$
      - id: ruff-format
        exclude: ^capture_tests/expected_captures\.txt$

  # - repo: https://github.com/numpy/numpydoc
  #   rev: v1.8.0
  #   hooks:
  #     - id: numpydoc-validation
  #       files: ^cbrain_cli/
  #       exclude: ^(capture_tests/|.*__init__\.py$)
